### ISSUE TITLE
Hosted on a maven repository?

### ISSUE THREAD

**Issue by gkatzioura** [GoogleCloudPlatform/kafka-pubsub-emulator#24]
Hi! 
Is there a maven repository in order to use the kafka-pubsub-emulator as an artifact?

**Comment by gkatzioura** [comment]
It seems not

**Comment by prodonjs** [comment]
My apologies for not seeing this in your first question. At this time there is no Maven repository and this project is no longer being actively supported. We're happy to take and review PRs but there is no feature roadmap at this time.

**Comment by gkatzioura** [comment]
Hi @prodonjs. May I upload this on maven by changing the package name?
