### ISSUE TITLE
SIGSEV using golang pub/sub client library

### ISSUE THREAD

**Issue by riccardomc** [GoogleCloudPlatform/kafka-pubsub-emulator#9]
Hi there, while performing some tests against the emulator I run into an issue using the [golang pub/sub client library](https://godoc.org/cloud.google.com/go/pubsub). I managed to consistently reproduce the issue with the following minimal go program:
```golang
func main() {
	project := "riccardomc-playground"
	subName := "subscription-topic1"
	ctx := context.Background()

	client, err := pubsub.NewClient(ctx, project)
	if err != nil {
		log.Fatalf("Client error: %v", err)
	}
	sub := client.Subscription(subName)

	config, err := sub.Config(ctx) // This breaks!

	if err != nil {
		log.Fatalf("Config error: %v", err)
	}

	log.Println(config)
}
```

Running the program above against the emulator (using [PUBSUB_EMULATOR_HOST](https://cloud.google.com/pubsub/docs/emulator) environment variable) above yields the following error:
```
% export PUBSUB_EMULATOR_HOST=192.168.99.100:30555 #this is where the emulator is running
% go run subscriber.go  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fd36b]

goroutine 1 [running]:
github.com/riccardomc/pubsubfun/vendor/cloud.google.com/go/pubsub.protoToSubscriptionConfig(0xc0001a8e00, 0xc0000aa7c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/rmc/Development/golang/src/github.com/riccardomc/pubsubfun/vendor/cloud.google.com/go/pubsub/subscription.go:189 +0x13b
github.com/riccardomc/pubsubfun/vendor/cloud.google.com/go/pubsub.(*Subscription).Config(0xc0000ac820, 0x9ab400, 0xc00009c010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/rmc/Development/golang/src/github.com/riccardomc/pubsubfun/vendor/cloud.google.com/go/pubsub/subscription.go:297 +0x11f
main.main()
	/home/rmc/Development/golang/src/github.com/riccardomc/pubsubfun/subscriber.go:21 +0x155
exit status 2
```
Please notice that each `sub.Receive` invokes a `sub.Config` call under the hood, which makes the go client library unusable with the emulator.

Moreover, running the same program against GCP pub/sub returns successfully:
```
% unset PUBSUB_EMULATOR_HOST                      
% go run subscriber.go                            
2018/11/19 20:46:21 {projects/riccardomc-playground/topics/topic1 { map[]} 10s false 168h0m0s map[]}
```
I suspect this is because the `Subscription` objects returned by the emulator don't set any value for `PushConfig`, while GCP does and the client library expects it. If I'll be able to confirm this I will file a PR.

It could also be a client library issue... let me know what do you think.

Also, thanks for this project! :blush:

**Comment by prodonjs** [comment]
Thanks for the issue report Riccardo. It definitely seems like the Go client-library expects the subscription to have at least a null PushConfig.

Try adding `.setPushConfig(PushConfig.getDefaultInstance())` at line 329 in SubscriberImpl and test against that emulator implementation. If that works, I'll happily take the PR.

**Comment by riccardomc** [comment]
Oops, I opend the PR before seeing your comment. I've applied `getDefaultInstance`.

**Comment by prodonjs** [comment]
Thanks for submitting. PR is merged. If you have any other issues or suggestions based on your usage of the emulator, let us know.

**Comment by riccardomc** [comment]
It appears this problem is back after the big refactor. Opening a separate issue as I cannot reopen this one.
